spring.application.name=erp

#DB config
spring.datasource.url=jdbc:mysql://localhost:3306/erp?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
#default server port 8080
#server.port=9090

# JWT Configuration
app.jwt.secret=YourSuperSecretKeyForERPApplication2026SecureJwtToken12345
app.jwt.expiration-ms=86400000
